---
title: "Arrays"
author: "Rafael Bueno - rm330593"
date: "26 de maio de 2018"
output: html_notebook
---

# Arrays

## Definição <- Estruturas homogêneas de várias dimensões

Vetores = arrays de 1 dimensão
Matrizes = arrays de 2 dimensões

```{r}
array(1:18, dim = c(3,3,2))
```

Criando vetores de tamanhos diferentes

```{r}
vector1 <- c(5,9,3)
vector2 <- c(10,11,12,13,14,15)
column.names <- c("COL1","COL2","COL3")
row.names <- c("ROW1","ROW2","ROW3")
matrix.names <- c("Matrix1","Matrix2")
```

Colocar os vetores em um array

```{r}
result <- array(c(vector1,vector2),dim = c(3,3,2),dimnames = list(row.names,
   column.names, matrix.names))
result
```

Trazer o resultado de pedaços do array

```{r}
print(result[3,,2])
print(result[1,3,1])
print(result[,,2])
```

## Cálculo dentre Arrays

Sintaxe <- apply(x, margin, fun)

* x = array
* margin = nome do dataset
* fun = nome da função

```{r}
new.array <- array(c(vector1,vector2),dim = c(3,3,2))
print(new.array)
```

```{r}
result.new <- apply(new.array, c(1), sum)
print(result.new)
```






